---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "auto" %>

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  #
  # repository
  #
  - name: repository
    run_list:
      - recipe[test::repository]
  #
  # client_install
  #
  - name: client_install
    run_list:
      - recipe[test::client_install]
  #
  # server_install
  #
  - name: server_install
    run_list:
      - recipe[test::server_install]
  #
  # server_configuration
  #
  - name: server_configuration
    run_list:
      - recipe[test::server_configuration]
  #
  # resources
  #
  - name: resources
    run_list:
      - recipe[test::user_database]
  #
  # replication
  #
  - name: replication
    run_list:
      - recipe[test::replication]
  #
  # datadir_changed
  #
  - name: datadir_changed
    run_list:
      - recipe[test::datadir_changed]
  #
  # port_changed
  #
  - name: port_changed
    run_list:
      - recipe[test::port_changed]
