---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.7
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  #
  # default
  #
  - name: default
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        use_default_repository: true
  #
  # native
  #
  - name: native
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        install:
          prefer_os_package: true
    includes:
      - centos-7.3
  #
  # scl
  #
  - name: scl
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        install:
          prefer_scl_package: true
    includes:
      - centos-7.3
      - centos-6.8
  #
  # replication
  #
  - name: replication
    run_list:
      - recipe[mariadb_test::replication]
    attributes:
      mariadb:
        use_default_repository: true
  #
  # galera
  #
  - name: galera
    run_list:
      - recipe[mariadb::galera]
    attributes:
      mariadb:
        use_default_repository: true
  #
  # datadir_changed
  #
  - name: datadir_changed
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        use_default_repository: true
        mysqld:
          datadir: /home/mysql
  #
  # port_changed
  #
  - name: port_changed
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        server_root_password: gsql
        use_default_repository: true
        mysqld:
          port: 3307
  #
  # plugins
  #
  - name: plugins
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        use_default_repository: true
        plugins:
          audit: true
  #
  # no_binlog
  #
  - name: no_binlog
    run_list:
      - recipe[mariadb::default]
    attributes:
      mariadb:
        use_default_repository: true
        replication:
          log_bin: false
