version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.0

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken-single:
          name: centos-6-repository
          platform: centos-6
          suite: repository
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-repository
          platform: centos-7
          suite: repository
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-repository
          platform: debian-9
          suite: repository
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-repository
          platform: debian-10
          suite: repository
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-6-client-install
          platform: centos-6
          suite: client-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-client-install
          platform: centos-7
          suite: client-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-client-install
          platform: debian-9
          suite: client-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-client-install
          platform: debian-10
          suite: client-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-6-server-install
          platform: centos-6
          suite: server-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-server-install
          platform: centos-7
          suite: server-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-server-install
          platform: debian-9
          suite: server-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-server-install
          platform: debian-10
          suite: server-install
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-6-server-configuration
          platform: centos-6
          suite: server-configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-server-configuration
          platform: centos-7
          suite: server-configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-server-configuration
          platform: debian-9
          suite: server-configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-server-configuration
          platform: debian-10
          suite: server-configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-configuration
          platform: debian-9
          suite: configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-configuration
          platform: debian-10
          suite: configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-6-resources
          platform: centos-6
          suite: resources
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-resources
          platform: centos-7
          suite: resources
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-resources
          platform: debian-9
          suite: resources
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-resources
          platform: debian-10
          suite: resources
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-6-replication
          platform: centos-6
          suite: replication
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-replication
          platform: centos-7
          suite: replication
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-replication
          platform: debian-9
          suite: replication
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-replication
          platform: debian-10
          suite: replication
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-6-datadir-changed
          platform: centos-6
          suite: datadir-changed
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7-datadir-changed
          platform: centos-7
          suite: datadir-changed
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-datadir-changed
          platform: debian-9
          suite: datadir-changed
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-galera-configuration
          platform: debian-9
          suite: galera-configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-9-port-changed
          platform: debian-9
          suite: port-changed
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-datadir-changed
          platform: debian-10
          suite: datadir-changed
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-galera-configuration
          platform: debian-10
          suite: galera-configuration
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-10-port-changed
          platform: debian-10
          suite: port-changed
          requires: [ lint, danger ]
